### ISSUE TITLE
Dashboard fails to build filtered queries

### ISSUE THREAD

**Issue by aryelevin** [ParsePlatform/parse-dashboard#164] opened 2016-03-18 09:16 UTC
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [V] You're running version >=2.1.4 of Parse Server.

- [V] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
Parse server v2.1.6.
Parse dashboard latest version from npm (1.0.2).
Using Safari 9.0.3.

#### Steps to reproduce
Apply any filter, or click pointer/relation cell, the issue is that the query is built with some Object instead a string/number as follows:
Query: {"where":{"weight":{"$exists":true}},"limit":200,"order":"**[objectObject],-createdAt**","_method":"GET","_ApplicationId":"lhnZMAtTWjw6mHpqmwD1sLLIjl9ABTemUIB7zLb0","_ClientVersion":"js1.6.14","_MasterKey":"POItvnF5ntnD2clbj7oFoAYNDIjN7EA6kmBVakgl","_InstallationId":"ecc64e34-9329-82eb-a290-29604b22ee31"}
Response: {"code":105,"error":"invalid key name: [objectObject]"}

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.
None

**Comment by darkkiss** [comment] 2016-03-21 07:59
I cannot reproduce this on 1.0.3

**Comment by drew-gross** [comment] 2016-03-21 19:11
Yep, this should be fixed in 1.0.3

**Closed by drew-gross** 2016-03-21 19:11 UTC

**Comment by aryelevin** [comment] 2016-03-21 19:25
Yep, that fixed in 1.0.3, Thanks!!!
