### ISSUE TITLE
Cannot change User object password

### ISSUE THREAD

**Issue by barnaclejive** [ParsePlatform/parse-dashboard#231] opened 2016-04-05 22:13 UTC
The parse-dashboard has no **Password** column on the **User** objects like the parse.com dashboard does.

- Is this intentional for some technical reason or can it be added?
- Is there some other way we should be managing User passwords after a migration to parse-server and parse-dashboard?

- [ x] You're running version >=2.1.4 of Parse Server.

- [ x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

**Comment by drew-gross** [comment] 2016-04-05 22:17
I see a password column on my dashboard. Can you make sure your Server and Dashboard versions are both up to date an check again?

**Comment by barnaclejive** [comment] 2016-04-06 00:53
@drew-gross I verified I am running:
parse-dashboard 2.1.6 dashboard
parser-server-example 1.4.0 which uses 
parse-server ~2.2.2. I still do not see a password column on the User table in parse-dashboard. Any ideas? Thanks.
![parse_dashboard](https://cloud.githubusercontent.com/assets/5251331/14302550/d10cf834-fb67-11e5-9039-405f91639796.png)

**Comment by drew-gross** [comment] 2016-04-06 01:09
Can you show me the response to the `schemas` endpoint, and also show if there are any errors in the Javascript console? Also, the most recent version of the dashboard is 1.0.8, so I think you might be confused about which version you are running.

**Comment by barnaclejive** [comment] 2016-04-06 03:09
@drew-gross You're right, I was on 1.07 of dashboard. I have moved to 1.0.8 now, no password column still though. Looking at the _SCHEMA for _User, I don't see the _hashed_password field mentioned, however it does show up in each _User document. See [gist here](https://gist.github.com/barnaclejive/c13e9c2ba38c5ba97a3adaf68529ff46). I'm going to try running a migration again, maybe there was an error moving the schema over?

**Comment by drew-gross** [comment] 2016-04-06 03:20
_hashed_password isn't supposed to show up in the _SCHEMA. I'm looking for the response to the `schemas` endpoint though. Just head to the API Console, use `schemas` as your endpoint, make sure to use the master key, and show me what you get. Also can you check the JavaScript console in your browser for errors?

**Comment by barnaclejive** [comment] 2016-04-06 03:30
@drew-gross 
Gotcha, here is the [`schemas ` output from API Console](https://gist.github.com/barnaclejive/b71393b9822c421ae47e3fdb7fc6eea2)
As far as js console, I only see a warning when I view the User collection:
`dashboard.bundle.js:19129 Warning: AppsSelector is accessing getDOMNode or findDOMNode inside its render(). render() should be a pure function of props and state. It should never access something that requires stale data from the previous render, such as refs. Move this logic to componentDidMount and componentDidUpdate instead.`

**Comment by drew-gross** [comment] 2016-04-06 03:43
Can you try clearing out your localstorage? We store column ordering and width in localstorage and if it got screwed up somehow that might cause this problem.

**Comment by barnaclejive** [comment] 2016-04-06 03:56
@drew-gross 
Cleared local storage and even tried it in a souple browsers where I had never run dashboard previously, no luck. After reloading dashboard and viewing User, my local storage for that page is:
`[{"name":"objectId","width":150},{"name":"sharePhotos","width":150},{"name":"emailVerified","width":150},{"name":"ACL","width":150},{"name":"freeVersion","width":150},{"name":"updatedAt","width":150},{"name":"freeUpgraded","width":150},{"name":"username","width":150},{"name":"petSortType","width":150},{"name":"createdAt","width":150},{"name":"email","width":150}]`

**Comment by barnaclejive** [comment] 2016-04-06 04:04
Compared to parse.com's dashboard, it appears that the local storage for parse-dashbord differs by the 'authData' and 'password' fields being missing. API Console output for schemas looks the same for _User between the two.

**Comment by drew-gross** [comment] 2016-04-06 04:09
Unfortunately I can't reproduce this issue :( are you comfortable with JavaScript and React? Would you be willing to install from source and investigate this bug? The list of columns is built up in `Browser.react.js` in the function `renderContent`. Alternatively, if you can message me with a URL that I can access your browser at (with different apps/master keys obviously) then I might be able to help.

**Comment by barnaclejive** [comment] 2016-04-06 04:43
=( I could try, right now I'm trying to get the dashboard up pointed at a debug copy of the app server. So maybe you could go there to see the issue. It appears to be deploying ok but won't load due to a JavaScript error `Uncaught SyntaxError: Unexpected token <               dashboard.bundle.js:1`

**Comment by drew-gross** [comment] 2016-04-06 05:08
I've traced the issue to a problem in Parse Server. I'll close this and open a new issue over there.

**Closed by drew-gross** 2016-04-06 05:08 UTC

**Comment by drew-gross** [comment] 2016-04-06 05:09
Essentially, your _SCHEMA collection doesn't contain the `password` field. It shouldn't be necessary to for it to be there - Parse.com works without the `password` field being in the schema, so Parse Server should too.

**Comment by barnaclejive** [comment] 2016-04-06 14:41
Thanks @drew-gross, I'll track the issue over on parser-server.
