### ISSUE TITLE
Feature Request: Add User to Role

### ISSUE THREAD

**Issue by neophob** [ParsePlatform/parse-dashboard#406] opened 2016-06-09 00:34 UTC
I would like to add specific users to an existing role. it's like an admin role which I want to assign to selected users. 

It looks like that's currently not possible with the dashboard

**Comment by MobileVet** [comment] 2016-07-07 16:56
The core functionality that you are looking for is adding a relation from the dashboard.
Duplicate of #148

**Closed** 2016-07-09 05:22 UTC
Labels: duplicate
