### ISSUE TITLE
Relation is not handled

### ISSUE THREAD

**Issue by cyring** [ParsePlatform/parse-dashboard#337] opened 2016-05-12 11:15 UTC
#### Environment Setup

Running version 2.2.7 of Parse Server and version 1.0.10 of Dashboard in a self-hosted platform.

#### Steps to reproduce

Cloud code

1- Add an object relation in the User class,
    where dbUser = request.user , the calling user;
    and dbMsg = the object to add a relation with.
```
var RelationAddMessage = function(dbUser, dbMsg, res) {
	var relation = dbUser.relation("message");
	    relation.add(dbMsg);

	dbUser.save(null, {
		success: function() { res.success(true); },
		error: function(_error) { res.error(_error); }
	} );
}
```
2- Into the dashboard, a new column "message" is added to the User class

3- Click the cell of relation, nothing happens. The browser is not forward to the Message class.

4- However, an iOS client is able to retrieve the record
```
let msgRelation = dbUser.relationForKey("message")
let msgQuery = msgRelation.query()
	msgQuery.findObjectsInBackgroundWithBlock( { (all: [PFObject]?, error: NSError?) -> Void in
//      ...
        } )
```
#### Logs/Trace
No log, dashboard remains silent.

**Comment by drew-gross** [comment] 2016-05-12 22:46
Currently there is a bug where filters in the source class will also apply to the relation. Do you think this might be that bug?

If not, can you install from source and use `npm dev dashboard`, then show any logs that show up in the console?

**Comment by cyring** [comment] 2016-05-15 17:46
This is issue is gone by modifying the upper level code. Nothing relative to filters.

**Comment by drew-gross** [comment] 2016-05-16 18:54
OK, that sounds like a duplicate of #241 so I'm going to close this.

**Closed by drew-gross** 2016-05-16 18:54 UTC
