### ISSUE TITLE
Delete all rows in collection

### ISSUE THREAD

**Issue by flessard** [ParsePlatform/parse-dashboard#124] opened 2016-03-10 19:54 UTC
Where is the delete all rows for a collection?

- [X] You're running version >=2.1.4 of Parse Server.

- [X] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

**Comment by DazChong** [comment] 2016-03-11 07:02
+1 I use mongo to drop collection.

**Comment by AmbroiseCollon** [comment] 2016-04-05 09:27
+1 would be useful for testing

**Comment by miracle7** [comment] 2016-04-14 04:13
+1

**Comment by hl4hck** [comment] 2016-04-23 15:35
+1

**Comment by adampietrasiak** [comment] 2016-05-18 22:11
+1

**Comment by JustinDMoore** [comment] 2016-05-19 17:52
+1

**Comment by adampietrasiak** [comment] 2016-05-25 15:12
Maybe at least some "Select all on screen" option on data browser?

Some websites have also such option that if I press mouse button on some checkbox and then (without releasing it) I move mouse to other checkboxes, they get selected too. That would save me a lot of clicking.

**Comment by quaz3l** [comment] 2016-05-26 16:37
Can someone explain why this checkbox in the header of collections is disabled?
![](https://i.imgur.com/1xXq87s.png)
I assume it would be for performance reasons? But If you inspect element, and enable it, it works and selects every element in the collection. It doesn't actually delete everything because it is probably a special case in code, but I could fix that to work as if every row was selected manually.

We could also just limited it to remove only 50 rows at a time to prevent overloading the server. Would this work?

**Comment by drew-gross** [comment] 2016-05-26 17:32
We disabled it because it was confusing some people, and a few people accidentally deleted their entire collection. We were eventually going to change it so it selected only the  visible rows, but we never got around to that.

**Comment by andrew8712** [comment] 2016-06-30 08:13
>We disabled it because it was confusing some people, and a few people accidentally deleted their entire collection.

Well, I believe that disabled *select all* checkbox abuses people even more.

If few people accidentally deleted their entire collection, that's their problem. Do we have to find a workarounds because they are not smart enough to avoid pressing `Delete` button when all rows are selected?

**Comment by JustinDMoore** [comment] 2016-06-30 12:10
Agree with @andrew8712 . Aren't they presented with a confirmation to delete, forcing them to type in the class name to confirm?

**Comment by grassland-curing-cfa** [comment] 2016-07-05 05:48
Deployed the latest Parse-server 2.2.15 and Parse-dashboard 1.0.14.
When I ran "Delete all rows" from the Edit menu list, it gave me a "404 Not Found" error when it tried to run "DELETE clear", which was identified from my Firebug console.
Also, "Select all" was disabled.

**Comment by benpackard** [comment] 2016-07-11 20:02
I don't see it mentioned here, but the 'Delete all rows' option also seems to do nothing. Is that also expected behavior? If so, should it be disabled in a similar fashion to the 'select all' checkbox?

Secondly, is deleting the mongoDB collection an appropriate alternative without additional side-effects?

**Comment by aksperiod** [comment] 2016-07-13 14:24
+1

**Comment by drew-gross** [comment] 2016-07-15 06:41
Should be fixed in 1.0.15 as long as you have the latest Parse Server.

**Closed by drew-gross** 2016-07-15 06:41 UTC
Labels: enhancement, good-first-pr, help wanted

**Comment by owldesign** [comment] 2016-10-11 21:36
For people who still have disabled checkbox (old forks)..

Quick workaround would be to inspect the checkbox and remove `disabled` attribute, then you can use it to check all entries and remove them..
