### ISSUE TITLE
Clicking Class name displays no results. Database has records.

### ISSUE THREAD

**Issue by talkaboutdesign** [ParsePlatform/parse-dashboard#99] opened 2016-03-07 16:29 UTC
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [YES ] You're running version >=2.1.4 of Parse Server.

- [ YES] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup

Local 

#### Steps to reproduce

If I inspect the page, I see the following error in the debugger: 

`XMLHttpRequest cannot load http://serverurlhere/parse/classes/Posts. Origin http://localhost:4040 is not allowed by Access-Control-Allow-Origin.`

#### Logs/Trace

**Comment by drew-gross** [comment] 2016-03-07 19:39
That error probably means the problem is with the server. Can you check what the request being sent to the server is, and what the response is? I'm going to close this and suggest that you re-open the issue on the Parse Server repo, but feel free to reopen this if it does turn out to be a dashboard issue.

**Closed by drew-gross** 2016-03-07 19:39 UTC
