### ISSUE TITLE
Parse Dashboard

### ISSUE THREAD

**Issue by thamer898** [ParsePlatform/parse-dashboard#78] opened 2016-03-06 16:25 UTC
Hello

When i locate to localhost:4040 only white screen appear can you help me please ?

Regards

**Comment by peterdotjs** [comment] 2016-03-06 16:36
Likely a duplicate of #75

**Comment by thamer898** [comment] 2016-03-06 16:43
Hello

How to solve this issue @peterdotjs ? can you help me

Regards

**Comment by peterdotjs** [comment] 2016-03-06 16:47
@thamer898 can you verify from your browser console that you're getting the same error? If so please close this issue and ref #75 for tracking.

**Comment by thamer898** [comment] 2016-03-06 16:52
Hello

yes i get the same error ?

Regards

**Closed** 2016-03-06 16:54 UTC
