### ISSUE TITLE
Config 403 Unauthorized. Unable to read, can create

### ISSUE THREAD

**Issue by Lunke** [ParsePlatform/parse-dashboard#631] opened 2017-01-15 15:36 UTC
Hey,
I have deployed Parse Dashboard to Heroku, and I can view and edit all the data in the browser section, but whenever I try to see the Config on the dashboard, I get error 403, Unauthorized. I can however create new parameters that will, if I check on Parse.com dashboard, be saved. 

I am using PARSE DASHBOARD 1.0.22.

**Comment by NatanRolnik** [comment] 2017-01-24 10:58
This is a duplicate of #596

**Comment by NatanRolnik** [comment] 2017-01-31 22:47
@Lunke this issue was fixed in the latest release.

**Closed** 2017-01-31 23:03 UTC
