### ISSUE TITLE
Cannot GET /login/

### ISSUE THREAD

**Issue by kwstasna** [ParsePlatform/parse-dashboard#607] opened 2016-12-02 12:31 UTC
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [x] You're running version >=1.0.20 of Parse Dashboard.

- [x] You're running version >=2.2.24 of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
Parse-Dashboard: 1.0.20
Parse-Server: 2.2.25
DigitalOcean Droplet
Nginx SetUp

#### Steps to reproduce

package.json

```
{
  "name": "parse-server-example",
  "version": "1.4.0",
  "description": "An example Parse API server using the parse-server module",
  "main": "index.js",
  "repository": {
    "type": "git",
    "url": "https://github.com/ParsePlatform/parse-server-example"
  },
  "license": "MIT",
  "dependencies": {
    "express": "~4.11.x",
    "kerberos": "~0.0.x",
    "parse": "~1.9.2",
    "parse-server": "~2.2.25",
    "parse-dashboard": "~1.0.20"
  },
  "scripts": {
    "start": "node index.js"
  },
  "engines": {
    "node": ">=4.3"
  }
}

```

index.js

```
// Example express application adding the parse-server module to expose Parse
// compatible API routes.

// Packtor Server
var express = require('express');  
var ParseServer = require('parse-server').ParseServer;  
var ParseDashboard = require('parse-dashboard');  
var path = require('path'); 

var databaseUri = process.env.DATABASE_URI || process.env.MONGODB_URI;

if (!databaseUri) {
  console.log('DATABASE_URI not specified, falling back to localhost.');
}

var api = new ParseServer({  
  verbose: true,
  databaseURI: databaseUri || 'mongodb://admin:dbpass@11.11.11.11/appDB',
  cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/cloud/main.js',
  appId: process.env.APP_ID || 'APPID',
  masterKey: process.env.MASTER_KEY || 'MUSTERKEY',
  serverURL: process.env.SERVER_URL || 'https://localhost:1337/parse',
  facebookAppIds: ['FBID'],
  fileKey: 'TEHFILEKEY'
});
// Client-keys like the javascript key or the .NET key are not necessary with parse-server
// If you wish you require them, you can set them as options in the initialization above:
// javascriptKey, restAPIKey, dotNetKey, clientKey

var app = express();

// Serve static assets from the /public folder
app.use('/public', express.static(path.join(__dirname, '/public')));

// Serve the Parse API on the /parse URL prefix
var mountPath = process.env.PARSE_MOUNT || '/parse';
app.use(mountPath, api);

// Parse Server plays nicely with the rest of your web routes
app.get('/', function(req, res) {
  res.status(200).send('I dream of being a website.  Please star the parse-server repo on GitHub!');
});

// There will be a test page available on the /test path of your server url
// Remove this before launching your app
app.get('/test', function(req, res) {
  res.sendFile(path.join(__dirname, '/public/test.html'));
});

var port = process.env.PORT || 1337;
var httpServer = require('http').createServer(app);
httpServer.listen(port, function() {
    console.log('parse-server-example running on port ' + port + '.');
});


// Set up parse dashboard
var dashboard = new ParseDashboard({  
  "apps": [{
      "serverURL": 'https://example.gr/parse', // Not localhost
      "appId": 'APPID',
      "masterKey": 'MUSTERKEY',
      "appName": "EXAMPLE",
      "production": false,
      "iconName": "yumyumicon.png",
  }],
  "users": [
    {
      "user":"admin",
      "pass":"password"
    }
  ],
  "iconsFolder": "icons"
});

var dashApp = express();

// make the Parse Dashboard available at /dashboard
dashApp.use('/dashboard', dashboard);  

// Parse Server plays nicely with the rest of your web routes
dashApp.get('/', function(req, res) {  
  res.status(200).send('Parse Dashboard App');
});

var httpServerDash = require('http').createServer(dashApp);  
httpServerDash.listen(4040, function() {  
    console.log('dashboard-server running on port 4040.');
});
```

Nginx configuration file `default`

```
# HTTP - redirect all requests to HTTPS
server {
    listen 80;
    listen [::]:80 default_server ipv6only=on;
	server_name EXAMPLE.GRwww.EXAMPLE.GR;
    return 301 https://$host$request_uri;
}

# HTTPS - serve HTML from /usr/share/nginx/html, proxy requests to /parse/
# through to Parse Server
server {
        listen 443 ssl;
        server_name EXAMPLE.GRwww.EXAMPLE.GR;
		
        root /usr/share/nginx/html;
        index index.html index.htm;

        ssl on;
        # Use certificate and key provided by Let's Encrypt:
        ssl_certificate /etc/letsencrypt/live/EXAMPLE.GR/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/EXAMPLE.GR/privkey.pem;
        ssl_session_timeout 5m;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_prefer_server_ciphers on;
        ssl_ciphers 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';

        # Pass requests for /parse/ to Parse Server instance at localhost:1337
location /parse {
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-NginX-Proxy true;
    proxy_pass http://localhost:1337;
    proxy_set_header Host $http_host;
    proxy_redirect off;
}
location /public/ {
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-NginX-Proxy true;
                proxy_pass http://localhost:1337/public/;
                proxy_ssl_session_reuse off;
                proxy_set_header Host $http_host;
                proxy_redirect off;
        }
location /test/ {
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-NginX-Proxy true;
                proxy_pass http://localhost:1337/test/;
                proxy_ssl_session_reuse off;
                proxy_set_header Host $http_host;
                proxy_redirect off;
        }
location /dashboard {
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-NginX-Proxy true;
    proxy_pass http://localhost:4040/dashboard/;
    proxy_set_header Host $http_host;
    proxy_redirect off;

    } 

location /login {
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-NginX-Proxy true;
    proxy_pass http://localhost:4040/login/;
    proxy_set_header Host $http_host;
    proxy_redirect off;
}      
}
```

And when i put on my browser the address

`https://example.gr/dashboard`

i get redirected at

`https://example.gr/login`

and it has an error

`Cannot GET /login/`

Although if i join 

`https://example.gr/test/`
It's working normally as it should.
I get the `test` page where i can post etc.
This means that nginx configuration is all setup well.
Am i missing anything at my other files?

P.S.

I stopped Nginx `sudo service nginx stop`
and i tried only with the IP

`11.11.11.11:4040/login`
and i still get this error.

**Comment by flovilmart** [comment] 2016-12-02 13:22
Duplicate of #604

**Closed by flovilmart** 2016-12-02 13:22 UTC
