### ISSUE TITLE
HTTPS Basic Auth not working

### ISSUE THREAD

**Issue by vferdiansyah** [ParsePlatform/parse-dashboard#143] opened 2016-03-15 05:14 UTC
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [X] You're running version >=2.1.4 of Parse Server.

- [X] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

I already setup HTTPS Basic Auth for my Parse Dashboard but it doesn't seem to work since there's no prompt to input username and password whatsoever when I open the dashboard URL on browser. I can basically do anything with my database as anonymous user.

![screen_shot_2016-03-15_at_12_01_29](https://cloud.githubusercontent.com/assets/12978330/13768289/d48a330e-eaa6-11e5-916c-c947effca869.jpg)

#### Environment Setup
Ubuntu 14.04 64 bit
Parse-Server 2.1.6
NodeJS 3.4.2
npm 3.8.1

#### Steps to reproduce
Access https://your_url:4040/apps/

**Comment by fxredeemer** [comment] 2016-03-15 08:08
In my case it workes fine, when accessing https://my_url:4040/apps/ a log in prompt is shown (only at first time after setting the password, afterwards it does not ask anymore)

**Comment by drew-gross** [comment] 2016-03-15 14:43
I am also unable to reproduce this. Are you sure you didn't enter your password once to load the file? Try opening your dashboard in a private/incognito window and see if you are asked for a password.

**Comment by vferdiansyah** [comment] 2016-03-15 16:05
@drew-gross nope, I never enter anything because I never prompted anything. Tried in incognito but also not working. Really strange...

**Comment by drew-gross** [comment] 2016-03-15 19:28
OK, since I'm unable to reproduce I will need to ask you for some help with debugging. Can you open that `Parse Dashboard/index.js` file, add 
```
console.log(users);
console.log(auth);
```
right before the `return res.send(response);` on line 75, the restart and reload the dashboard and show my what the output it?

**Comment by vferdiansyah** [comment] 2016-03-15 23:41
@drew-gross strange. nothing seems to come out of the log :/
I'll dig deeper to my server configuration.

**Comment by drew-gross** [comment] 2016-03-25 00:25
Closing this issue since it's now over a week old.

**Closed by drew-gross** 2016-03-25 00:25 UTC
